---
title: "Captial_Bike_Share"
author: "GAYATHRI cHANDRASEKARAN"
date: "11/14/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r basicfcn, include=F}
# can add quietly=T option to the require() function
loadPkg = function(x) { if (!require(x,character.only=T, quietly =T)) { install.packages(x,dep=T,repos="http://cran.us.r-project.org"); if(!require(x,character.only=T)) stop("Package not found") } }
```


```{r}
bike <- read.csv("./rawF_CapitalBikeShare.csv")
```


```{r}
Bike1 <- subset(bike, select = -c(Start.station,Wind,Wind.Gust..mph.,Pressure..in.,Precip...in.))
```

```{r}
Bike1$Condition <- as.character(Bike1$Condition)
Bike1$Condition[Bike1$Condition %in% c("Cloudy","Cloudy / Windy","Mostly Cloudy","Mostly Cloudy / Windy","Partly Cloudy","Partly Cloudy / Windy")] <- "Cloudy"
Bike1$Condition[Bike1$Condition %in% c("Squalls / Windy","Thunder","Thunder / Windy","Thunder in the Vicinity","Wintry Mix","Wintry Mix / Windy")] <- "Windy"
Bike1$Condition[Bike1$Condition %in% c("Fair","Fair / Windy")] <- "Fair"
Bike1$Condition[Bike1$Condition %in% c("Fog","Mist","Patches of Fog","Shallow Fog","Haze")] <- "Fog"
Bike1$Condition[Bike1$Condition %in% c("Heavy Rain","Heavy Rain / Windy","Light Rain","Light Rain / Windy","Light Rain with Thunder","Rain","Rain / Windy","Light Drizzle","Light Drizzle / Windy","Heavy T-Storm","Heavy T-Storm / Windy","T-Storm","T-Storm / Windy")]<-"Rain"
Bike1$Condition[Bike1$Condition %in% c("Heavy Snow","Light Freezing Drizzle","Light Sleet","Light Sleet / Windy","Light Snow","Light Snow / Windy","Light Snow and Sleet","Light Snow and Sleet / Windy","Rain and Sleet","Rain and Snow","Sleet","Snow","Snow and Sleet","Light Freezing Rain")]<-"Snow"
```

```{r}
loadPkg("dplyr")
Bike1 <- mutate(Bike1, Holiday = ifelse(is.na(Holiday),0,Holiday))
Bike1$Holiday[Bike1$Holiday > 0] <- 1
```

```{r}
Bike1 <- subset(Bike1, Condition != "")
```

```{r}
Bike2 <- Bike1 %>% group_by(Start.date) %>% summarise(Total_Bikes = sum(noOfBikes)) %>% left_join( subset(Bike1, select=-noOfBikes), by = "Start.date")%>% distinct(Start.date,.keep_all = TRUE) %>% arrange(Start.date)
```

```{r}
colnames(Bike2) <- c("Start_Date","Total_Bikes","Condition","Temp","Dew","Humidity","Windspeed","Holiday","Weekday","TimeofDay",
                     "Season")
```

```{r}
Bike2[c(4,5,6,7)] <- lapply(Bike2[c(4,5,6,7)], function(x) c(scale(x)))
```

```{r}
loadPkg("lubridate")
Bike2$HourOfDay <- hour(Bike2$Start_Date)
Bike2$Month <- month(Bike2$Start_Date)
Bike2$Day <- day(Bike2$Start_Date)
Bike2$Year <- year(Bike2$Start_Date)
```


```{r}
Bike2 <- Bike2[c(1,3:15,2)]
```

```{r}
summary(Bike2)
```

```{r}
str(Bike2)
```

```{r}
Bike2$HourOfDay <- as.factor(Bike2$HourOfDay)
Bike2$Month <- as.factor(Bike2$Month)
Bike2$Year <- as.factor(Bike2$Year)
Bike2$Day <- as.factor(Bike2$Day)
Bike2$Condition <- as.factor(Bike2$Condition)
Bike2$Holiday <- as.factor(Bike2$Holiday)
```



```{r}
Training_Set <- subset(Bike2, Year %in% c(2013,2014,2015,2016,2017,2018))
Test_Set <- subset(Bike2, Year %in% c(2019))
```

```{r}
#X_train <- subset(Training_Set, select = -c(Start_Date,Total_Bikes))
#Y_train <- subset(Training_Set, select = Total_Bikes)
```

```{r}
Training_Set <- subset(Training_Set, select = -c(Start_Date,Month,Day,Year))
```

```{r}
names(Training_Set)[11] <- "y"
```


```{r}
loadPkg("leaps")
reg.leaps <- regsubsets(y~., data = Training_Set, nbest = 1, method = "forward")  # leaps, 
plot(reg.leaps, scale = "adjr2", main = "Adjusted R^2")
plot(reg.leaps, scale = "bic", main = "BIC")
plot(reg.leaps, scale = "Cp", main = "Cp")
detach("package:leaps", unload = T) # good habit to remove unload packages no longer needed 
```


```{r}
lm_fit <- lm(y~.,data = Training_Set)
summary(lm_fit)
loadPkg("faraway")
vif(lm_fit)
```


```{r}
loadPkg("randomForest")

```

```{r}
fit <- randomForest(y ~ .,   data=Training_Set)
summary(fit)
plot(importance(fit))
```






